language: node_js
deploy:
  provider: heroku
  api_key:
    secure: dE0Rd/shYBr6c5Jm9VRUfrr+GoPO7z5D7ATzJ/geo6qadolx4u4J5Cos4UiEbgRTkoR8T/dnxCErH0djF5ot0iyPJO7M0VBZLynT3XVkHUrDq52jvtOei5nZAXrtG7vBjNC0Ok9A0uL72FxJfZTVnPLp4p6VYJIj4GuTcOP2SrW98jHEax0lJjSVdXnvWepvARYokA0n/8zBEfYSs8NWZ6tAz24ZpsUTsjHzbLvc6rp57uZW5hlQxRcSgEl1+GeYzkiw7B93qQhpSkc7onNg9jG5lA/6NzXuY5L1ENoGYzhVJL+QCvhoSWWC5xVCSWR01kDfYWr4f8psRplMIpHylfCbZZFVO4ZNk0Zm0Y4Cic2HjAynVj19sMXKv6yIFjgtRdVREDz44N//UAcRgNLU7rUG0X5e/62B3L6tZNUP8mk8g+G/8AI4UjA5XzUbbOVtTFNDBx9MO6wszKFuul0mXy3KTkyVlVU6fOEglKyhtyAjxbWHwFOX6gnrc+sR2yviwjauU173JgPtXiSZmjUpy9m5hCY3Wo7N5m3E7pr/6xat+5I/XyClcd/YlyAaGoV0EUKo68dx0V13h5zg5rUWSEamh+iiCemqyce2Lr/p7RXOqkiCLKNtak46wyud9dbOtbVLVK02TrSTC4JgfEhH7Oc9ln30veLhvFoHtgRuB8Q=
  app: enigmatic-wave-69804
  on:
    repo: HeyArnold-Flexing/habitlogger
